version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    image: ${CRAWLER_IMAGE_NAME:-crawler:latest}
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - migration
      - db

  migration:
    image: ${CRAWLER_IMAGE_NAME:-crawler:latest}
    command: python manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db