# Generated by Django 3.2.20 on 2023-07-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='ability_name',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
