# Generated by Django 3.2.20 on 2023-07-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_information', '0003_auto_20230728_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='species_color',
            field=models.CharField(max_length=15),
        ),
    ]
